gui:
  theme:
    activeBorderColor:
      - "#8ba4b0"
      - bold
    inactiveBorderColor:
      - "#625e5a"
    optionsTextColor:
      - "#7fb4ca"
    selectedLineBgColor:
      - "#282727"
    cherryPickedCommitBgColor:
      - "#393836"
    cherryPickedCommitFgColor:
      - "#87a987"
    unstagedChangesColor:
      - "#c4746e"
    defaultFgColor:
      - "#c5c9c5"
    searchingActiveBorderColor:
      - "#c4b28a"

  authorColors:
    "*": "#a292a3"
