backend = "glx";
vsync = true;
glx-use-copysubbuffer-mesa = true;

glx-copy-from-front = true;
glx-swap-method = 2;
xrender-sync = true;
xrender-sync-fence = true;

# Enable/disable picom's shadow effect
shadow = false;

# Fading settings
fading = true;
fade-delta = 12;

# Opacity of inactive windows
inactive-opacity = 1.0;

# Opacity of active windows
active-opacity = 1.0;

# Opacity for specific windows, based on class name
opacity-rule = ["80:class_g = 'WezTerm'"];

# Enable transparency
transparent-clipping = true;

# Background opacity settings
frame-opacity = 0.8;
inactive-opacity-override = true;

shadow-exclude = [
    "class_g = 'i3-frame'",
    "class_g = 'i3bar'",
    "class_g = 'i3' && !window_type = 'normal'"
];

no-dock-shadow = true;


