gui:
  theme:
    activeBorderColor:
      - "#a7c080"
      - bold
    inactiveBorderColor:
      - "#2d353b"
    optionsTextColor:
      - "#dbbc7f"
    selectedLineBgColor:
      - "#232a2e"
    cherryPickedCommitBgColor:
      - "#374145"
    cherryPickedCommitFgColor:
      - "#83c092"
    unstagedChangesColor:
      - "#e67e80"
    defaultFgColor:
      - "#d3c6aa"
    searchingActiveBorderColor:
      - "#a7c080"

  authorColors:
    "*": "#d699b6"
